Better search function
filcnaplo/filcnaplo pull request #51
Opened 2020-10-05 18:27 UTC by CoderCharmander

A keresőmezőbe a megfelelő `tag`-eket beírva kiadja az azt birtokló elemeket: pl. a "matematika 25%" kifejezés a 25%-os súlyú matematika jegyeket adta ki. A keresést valamennyire újraírtam, hogy a Dart beépített lista-manipulációs metódusait használja.

A jegyek automatikusan megkapják az alábbi tageket:
- Tárgy
- Súly + `'%'`
- i18n "grade", nyelvfüggő

Az üzenetek:
- Tárgy
- i18n "message", nyelvfüggő

Példa:
![Screenshot_1601922038](https://user-images.githubusercontent.com/42486026/95117560-14ecc380-0749-11eb-9386-a5f3d428d93b.png)
![Screenshot_1601922053](https://user-images.githubusercontent.com/42486026/95117562-161df080-0749-11eb-8f47-1acdfab489e9.png)
![Screenshot_1601922058](https://user-images.githubusercontent.com/42486026/95117564-16b68700-0749-11eb-9fb2-0866f9937ce8.png)

2020-10-08 13:38 UTC, RedyAu requested changes
Az ötlet jó, de szerintem felesleges ennyi plusz elem, csak lassítja.
Talán elég lenne a keresőstring végére rakosgatni a tageket (hiába szebb így sokkal).
Vélemény @UnknownPlayer78 ?

2020-10-08 13:50 UTC, RedyAu approved these changes

2020-10-08 16:28 UTC, CoderCharmander commented
Azért adtam hozzá így, mert egyébként egy tag részleges beírásakor rögtön kidobná azt, pl. ha elkezdem írni, hogy "m", akkor rögtön kiadja a matekjegyeket, de az egy kicsit elterelő lehet. (De persze ez csak az én véleményem)

2020-10-08 16:37 UTC, Zoldszemesostoros commented
> egy tag részleges beírásakor rögtön kidobná azt
Szerintem ez a "normális" viselkedés, én legalábbis ezt várnám el tőle. Nincs ezzel semmi baj.

2020-10-14 08:28 UTC, RedyAu commented
@UnknownPlayer78 Jöhet?

2020-10-14 08:29 UTC, UnknownPlayer78 commented
meg nem neztem meg este megnezem

2020-10-14 18:45 UTC, merged