Közelgő dolgozatok
filcnaplo/filcnaplo pull request #54
Opened 2020-10-13 16:54 UTC by Zoldszemesostoros

A főoldalon - ha vannak - kilistázza a következő 3 nap dolgozatait.

2020-10-13 16:55 UTC, UnknownPlayer78 commented
legyszives screenshot es ha meg nincs kesz akkor ne nyiss prt

2020-10-13 17:11 UTC, RedyAu commented
Na még jó hogy ott hagytam a Now-t :D
Amúgy szerintem ez ilyen formában nem illik oda, nem kéne ennyire hasonlítania a kártyákhoz. Főleg ha majd más funkciókkal is bővül

2020-10-13 17:13 UTC, RedyAu requested changes
Na még jó hogy ott hagytam a Now-t :D
Amúgy szerintem ez ilyen formában nem illik oda, nem kéne ennyire hasonlítania a kártyákhoz. Főleg ha majd más funkciókkal is bővül

2020-10-13 17:15 UTC, Zoldszemesostoros commented
> Mennyire tekinted kesznek?

Eddig annak tekintettem, de ha @RedyAu - nak van valami javaslata, hogy hogyan kéne kinéznie, akkor azt még megcsinálom.

2020-10-13 17:17 UTC, RedyAu commented
Valahogy legyen más a kártya dizájnja, nem tudom, kísérletezz
A tervező oldal logója mehetne a cím elé és a dolgozatok elé meg egy-egy pötty mondjuk

2020-10-13 17:17 UTC, UnknownPlayer78 commented
hat meg eleg hianyos meg valoban nem is illik bele

2020-10-13 17:19 UTC, RedyAu commented
De ezekre amúgy van @UnknownPlayer78 részéről egy _grand vision_, de ha így folytatjuk, az nem biztos hogy hamar megvalósul, ha addig is ez pótolhatja, nagyon köszönjük.
Csak tényleg kicsit félkész hatása van.
Ötlet: A cím legyen kövérebb, kapitális, kisebb és accent color színű

2020-10-14 17:08 UTC, RedyAu commented
#31

2020-10-14 17:12 UTC, RedyAu approved these changes
Szerintem az amúgy is experimental "now" branchbe bejöhet, akár jelen állapotában is, az esetleges hiányosságait a béta program majd megtalálja.

2020-10-14 18:48 UTC, merged